/*********************************************************/
/* This file generated by GenHeader.bat from QinYiprot.h */
/* Do Not Modify this file                               */
/* Depend Files: qydef.awk/sed.exe/awk.exe               */
/*********************************************************/


extern QY_ADAPTOR * g_pMtk;

 

#define kal_wsprintf 	g_pMtk->qy_kal_wsprintf
#define kal_prompt_trace 	g_pMtk->qy_kal_prompt_trace

#define kal_wstrlen 	g_pMtk->qy_kal_wstrlen
#define kal_wstrcpy 	g_pMtk->qy_kal_wstrcpy
#define kal_wstrncpy 	g_pMtk->qy_kal_wstrncpy
#define kal_wstrcmp 	g_pMtk->qy_kal_wstrcmp
#define kal_wstrncmp 	g_pMtk->qy_kal_wstrncmp
#define kal_wstrcat 	g_pMtk->qy_kal_wstrcat
#define kal_wstrncat 	g_pMtk->qy_kal_wstrncat
#define kal_wstrchr 	g_pMtk->qy_kal_wstrchr
#define kal_wstrrchr 	g_pMtk->qy_kal_wstrrchr

#define mmi_ucs2toi 	g_pMtk->qy_mmi_ucs2toi
#define mmi_ucs2tox 	g_pMtk->qy_mmi_ucs2tox
#define mmi_asc_to_wcs 	g_pMtk->qy_mmi_asc_to_wcs
#define mmi_asc_n_to_wcs 	g_pMtk->qy_mmi_asc_n_to_wcs
#define mmi_wcs_to_asc 	g_pMtk->qy_mmi_wcs_to_asc
#define mmi_wcs_n_to_asc 	g_pMtk->qy_mmi_wcs_n_to_asc
#define mmi_asc_to_wcs_ex 	g_pMtk->qy_mmi_asc_to_wcs_ex
#define mmi_asc_n_to_wcs_ex 	g_pMtk->qy_mmi_asc_n_to_wcs_ex
#define mmi_wcslwr 	g_pMtk->qy_mmi_wcslwr
#define mmi_wcsupr 	g_pMtk->qy_mmi_wcsupr
#define mmi_wcsicmp 	g_pMtk->qy_mmi_wcsicmp
#define mmi_wcsnicmp 	g_pMtk->qy_mmi_wcsnicmp

#define FuncQyMalloc 	g_pMtk->qy_FuncQyMalloc
#define FuncQyFree 	g_pMtk->qy_FuncQyFree

#define StopTimer 	g_pMtk->qy_StopTimer
#define StartTimer 	g_pMtk->qy_StartTimer
#define StartTimerEx 	g_pMtk->qy_StartTimerEx
#define applib_dt_get_date_time 	g_pMtk->qy_applib_dt_get_date_time

#define playRequestedTone 	g_pMtk->qy_playRequestedTone
#define stopRequestedTone 	g_pMtk->qy_stopRequestedTone

#define FS_Open 	g_pMtk->qy_FS_Open
#define FS_Close 	g_pMtk->qy_FS_Close
#define FS_Read 	g_pMtk->qy_FS_Read
#define FS_Write 	g_pMtk->qy_FS_Write
#define FS_Seek 	g_pMtk->qy_FS_Seek
#define FS_Commit 	g_pMtk->qy_FS_Commit

#define FS_GetFileSize 	g_pMtk->qy_FS_GetFileSize
#define FS_GetFilePosition 	g_pMtk->qy_FS_GetFilePosition

#define FS_Delete 	g_pMtk->qy_FS_Delete
#define FS_CheckFile 	g_pMtk->qy_FS_CheckFile

#define FS_GetCurrentDir 	g_pMtk->qy_FS_GetCurrentDir
#define FS_SetCurrentDir 	g_pMtk->qy_FS_SetCurrentDir
#define FS_CreateDir 	g_pMtk->qy_FS_CreateDir
#define FS_RemoveDir 	g_pMtk->qy_FS_RemoveDir

#define FS_Rename 	g_pMtk->qy_FS_Rename
#define FS_XDelete 	g_pMtk->qy_FS_XDelete
#define FS_GetDrive 	g_pMtk->qy_FS_GetDrive

#define QySocketConnect 	g_pMtk->qy_QySocketConnect
#define soc_send 	g_pMtk->qy_soc_send
#define soc_recv 	g_pMtk->qy_soc_recv
#define soc_close 	g_pMtk->qy_soc_close

#define open_scan_engine 	g_pMtk->qy_open_scan_engine
#define trig_on_scan_engine 	g_pMtk->qy_trig_on_scan_engine
#define close_scan_engine 	g_pMtk->qy_close_scan_engine

#define wgui_status_icon_show_status_icon 	g_pMtk->qy_wgui_status_icon_show_status_icon
#define wgui_status_icon_hide_status_icon 	g_pMtk->qy_wgui_status_icon_hide_status_icon
#define wgui_status_icon_update_status_icons 	g_pMtk->qy_wgui_status_icon_update_status_icons
#define set_softkey_label 	g_pMtk->qy_set_softkey_label

#define get_image 	g_pMtk->qy_get_image
#define get_string 	g_pMtk->qy_get_string
#define GetRootTitleIcon 	g_pMtk->qy_GetRootTitleIcon

#define AddListSelItem 	g_pMtk->qy_AddListSelItem
#define AddListFullEditItem 	g_pMtk->qy_AddListFullEditItem
#define AddListItem 	g_pMtk->qy_AddListItem
#define ShowQinYiList 	g_pMtk->qy_ShowQinYiList

#define ShowQinYiMenu 	g_pMtk->qy_ShowQinYiMenu
#define mmi_scan_display_popup 	g_pMtk->qy_mmi_scan_display_popup

#define EntryNewScreen 	g_pMtk->qy_EntryNewScreen
#define GetActiveScreenId 	g_pMtk->qy_GetActiveScreenId
#define GetHistory 	g_pMtk->qy_GetHistory
#define GoBackHistory 	g_pMtk->qy_GoBackHistory
#define GoBackToHistory 	g_pMtk->qy_GoBackToHistory
#define GetCurrGuiBuffer 	g_pMtk->qy_GetCurrGuiBuffer
#define GetCurrInputBuffer 	g_pMtk->qy_GetCurrInputBuffer
#define DeleteScreens 	g_pMtk->qy_DeleteScreens
#define DeleteHistory 	g_pMtk->qy_DeleteHistory
#define DeleteNHistory 	g_pMtk->qy_DeleteNHistory
#define DeleteScreenIfPresent 	g_pMtk->qy_DeleteScreenIfPresent
#define IsScreenPresent 	g_pMtk->qy_IsScreenPresent
#define GetCurrNInputBuffer 	g_pMtk->qy_GetCurrNInputBuffer
#define SetDelScrnIDCallbackHandler 	g_pMtk->qy_SetDelScrnIDCallbackHandler
#define ClearDelScrnIDCallbackHandler 	g_pMtk->qy_ClearDelScrnIDCallbackHandler

#define GetHighlightedItem 	g_pMtk->qy_GetHighlightedItem
#define RegisterHighlightHandler 	g_pMtk->qy_RegisterHighlightHandler
#define ClearHighlightHandler 	g_pMtk->qy_ClearHighlightHandler
#define ChangeLeftSoftkey 	g_pMtk->qy_ChangeLeftSoftkey
#define ChangeRightSoftkey 	g_pMtk->qy_ChangeRightSoftkey
#define SetLeftSoftkeyFunction 	g_pMtk->qy_SetLeftSoftkeyFunction
#define SetRightSoftkeyFunction 	g_pMtk->qy_SetRightSoftkeyFunction
#define entry_full_screen 	g_pMtk->qy_entry_full_screen
#define leave_full_screen 	g_pMtk->qy_leave_full_screen

#define ExecuteCurrKeyHandler 	g_pMtk->qy_ExecuteCurrKeyHandler
#define GetkeyInfo 	g_pMtk->qy_GetkeyInfo
#define GetKeyHandler 	g_pMtk->qy_GetKeyHandler
#define SetKeyHandler 	g_pMtk->qy_SetKeyHandler
#define SetGroupKeyHandler 	g_pMtk->qy_SetGroupKeyHandler
#define ClearKeyHandler 	g_pMtk->qy_ClearKeyHandler
#define PowerAndEndKeyHandler 	g_pMtk->qy_PowerAndEndKeyHandler
#define ClearKeyEvents 	g_pMtk->qy_ClearKeyEvents

#define get_softkey_label 	g_pMtk->qy_get_softkey_label
#define set_softkey_icon 	g_pMtk->qy_set_softkey_icon
#define get_softkey_icon 	g_pMtk->qy_get_softkey_icon
#define change_softkey 	g_pMtk->qy_change_softkey
#define show_softkey 	g_pMtk->qy_show_softkey
#define clear_softkey_handler 	g_pMtk->qy_clear_softkey_handler

#define gdi_layer_lock_frame_buffer 	g_pMtk->qy_gdi_layer_lock_frame_buffer
#define gdi_layer_unlock_frame_buffer 	g_pMtk->qy_gdi_layer_unlock_frame_buffer

#define wgui_update_inline_data 	g_pMtk->qy_wgui_update_inline_data
#define QyAdpTrace 	g_pMtk->qy_QyAdpTrace
#define DisplayPopup 	g_pMtk->qy_DisplayPopup
#define DisplayConfirm 	g_pMtk->qy_DisplayConfirm
#define RedrawCategory57Screen 	g_pMtk->qy_RedrawCategory57Screen
#define SetHighlightIndex 	g_pMtk->qy_SetHighlightIndex
#define RedrawListCategoryScreen 	g_pMtk->qy_RedrawListCategoryScreen

#define InitializeCategory57Screen 	g_pMtk->qy_InitializeCategory57Screen
#define ExitCategory57Screen 	g_pMtk->qy_ExitCategory57Screen
#define CloseCategory57Screen 	g_pMtk->qy_CloseCategory57Screen
#define SetInlineItemActivation 	g_pMtk->qy_SetInlineItemActivation
#define DisableInlineItem 	g_pMtk->qy_DisableInlineItem
#define EnableInlineItem 	g_pMtk->qy_EnableInlineItem
#define LeftJustifyInlineItem 	g_pMtk->qy_LeftJustifyInlineItem
#define RightJustifyInlineItem 	g_pMtk->qy_RightJustifyInlineItem
#define CenterJustifyInlineItem 	g_pMtk->qy_CenterJustifyInlineItem
#define SetInlineDoneFlag 	g_pMtk->qy_SetInlineDoneFlag
#define DisableCategory57ScreenDone 	g_pMtk->qy_DisableCategory57ScreenDone
#define EnableCategory57ScreenDone 	g_pMtk->qy_EnableCategory57ScreenDone
#define SetCategory57ScreenRSKClear 	g_pMtk->qy_SetCategory57ScreenRSKClear
#define SetCategory57LeftSoftkeyFunction 	g_pMtk->qy_SetCategory57LeftSoftkeyFunction
#define SetCategory57RightSoftkeyFunctions 	g_pMtk->qy_SetCategory57RightSoftkeyFunctions
#define SetCategory57Data 	g_pMtk->qy_SetCategory57Data

#define SetInlineItemTextEdit 	g_pMtk->qy_SetInlineItemTextEdit
#define RegisterInlineTextEditValidationFunction 	g_pMtk->qy_RegisterInlineTextEditValidationFunction
#define SetInlineTextEditCustomFunction 	g_pMtk->qy_SetInlineTextEditCustomFunction
#define ReConfigureInlineItemTextEdit 	g_pMtk->qy_ReConfigureInlineItemTextEdit
#define inline_text_edit_set_RSK_label 	g_pMtk->qy_inline_text_edit_set_RSK_label
#define SetInlineItemFullScreenEdit 	g_pMtk->qy_SetInlineItemFullScreenEdit
#define RegisterInlineFullScreenEditValidationFunction 	g_pMtk->qy_RegisterInlineFullScreenEditValidationFunction
#define SetInlineItemMultiLineEdit 	g_pMtk->qy_SetInlineItemMultiLineEdit
#define SetInlineMultiLineRdOnly 	g_pMtk->qy_SetInlineMultiLineRdOnly
#define set_inscreen_multi_line_input_box_changed 	g_pMtk->qy_set_inscreen_multi_line_input_box_changed

#define SetInlineItemImageText 	g_pMtk->qy_SetInlineItemImageText
#define SetInlineItemCaption 	g_pMtk->qy_SetInlineItemCaption
#define SetInlineItemDisplayOnly 	g_pMtk->qy_SetInlineItemDisplayOnly
#define SetInlineItemSelect 	g_pMtk->qy_SetInlineItemSelect
#define RegisterInlineSelectHighlightHandler 	g_pMtk->qy_RegisterInlineSelectHighlightHandler
#define GetInlineSelectHighlightedItem 	g_pMtk->qy_GetInlineSelectHighlightedItem
#define SetInlineItemUserDefinedSelect 	g_pMtk->qy_SetInlineItemUserDefinedSelect
#define SetInlineItemDOWSelect 	g_pMtk->qy_SetInlineItemDOWSelect
#define SetInlineItemDate 	g_pMtk->qy_SetInlineItemDate
#define SetInlineItemTime 	g_pMtk->qy_SetInlineItemTime
#define SetInlineItemIP4 	g_pMtk->qy_SetInlineItemIP4
#define RegisterAttachmentLskFunction 	g_pMtk->qy_RegisterAttachmentLskFunction
#define RegisterAttachmentRskFunction 	g_pMtk->qy_RegisterAttachmentRskFunction
#define RegisterAttachmentHighlightedFunction 	g_pMtk->qy_RegisterAttachmentHighlightedFunction
#define SetInlineItemImageAttachment 	g_pMtk->qy_SetInlineItemImageAttachment
#define ClearAttachmentImage 	g_pMtk->qy_ClearAttachmentImage
#define AddEmailImageAttachmentUI 	g_pMtk->qy_AddEmailImageAttachmentUI
#define ClearAllAttachmentImages 	g_pMtk->qy_ClearAllAttachmentImages
#define SetHighlightedAttachment 	g_pMtk->qy_SetHighlightedAttachment
#define DisableInlineItemHighlight 	g_pMtk->qy_DisableInlineItemHighlight
#define EnableInlineItemHighlight 	g_pMtk->qy_EnableInlineItemHighlight

#define ShowCategory353Screen 	g_pMtk->qy_ShowCategory353Screen

#define ShowCategory57Screen_ex 	g_pMtk->qy_ShowCategory57Screen_ex

#define ShowCategory79Screen 	g_pMtk->qy_ShowCategory79Screen

#define ShowCategory111Screen 	g_pMtk->qy_ShowCategory111Screen
#define SetCategory111RightSoftkeyFunction 	g_pMtk->qy_SetCategory111RightSoftkeyFunction
#define wgui_inputs_register_validation_func 	g_pMtk->qy_wgui_inputs_register_validation_func



