{ 
	if( nlines == 0 )
	{
		printf( "/*********************************************************/\n");
		printf( "/* This file generated by GenHeader.bat from QinYiprot.h */\n");
		printf( "/* Do Not Modify this file                               */\n");
		printf( "/* Depend Files: exp.awk/sed.exe/awk.exe                 */\n");
		printf( "/*********************************************************/\n\n\n");
		printf("#define QY_ADAPTO_ELEMENT  {")
	}
	nlines++;
		
	if( ($1 !~ /^#/)  && ($1 !~ "typedef") && (index($0, "}") == 0))
	{ 
		if(NF >= 2 )
		{
			blast = 0;
			if( index($2,"(" ) != 0 )
			{
				printf("\t%s,\\\n",substr($2,1,index($2,"(" )-1) )
			}
			else
			{
				if( index($3,"(" ) != 0 )
					printf("\t%s,\\\n",$2 )
			}	
		}
		else
		{
			if( blast == 0 )
				printf("\t\\\n")
			blast = 1;
		}
	}
	
}

