{ 
	if( nlines == 0 )
	{
			printf( "/*********************************************************/\n");
			printf( "/* This file generated by GenHeader.bat from QinYiprot.h */\n");
			printf( "/* Do Not Modify this file                               */\n");
			printf( "/* Depend Files: qydef.awk/sed.exe/awk.exe               */\n");
			printf( "/*********************************************************/\n\n\n");		
		printf("extern QY_ADAPTOR * g_pMtk;\n\n ")
	}
	nlines++;		
	if( ($1 !~ /^#/)  && ($1 !~ "typedef") && (index($0, "}")== 0))
	{ 
		if(NF >= 2 )
		{
			blast = 0;
			if( index($2,"(" ) != 0 )
			{
				strfnx = substr($2,1,index($2,"(" )-1)
				printf("#define %s \tg_pMtk->qy_%s\n",strfnx, strfnx )
			}
			else
			{
				if( index($3,"(" ) != 0 )
					printf("#define %s \tg_pMtk->qy_%s\n",$2 ,$2)
			}	
		}
		else
		{
			if( blast == 0 )
				printf("\n")
			blast = 1;
		}
	}
	
}

