{ 
	if( ($1 !~ /^#/)  && ($1 !~ "typedef") && (index($0, "{")== 0) && (index($0, "}")== 0))
	{ 
		
		if( nlines == 0 )
		{
			printf( "/*********************************************************/\n");
			printf( "/* This file generated by GenHeader.bat from QinYiprot.h */\n");
			printf( "/* Do Not Modify this file                               */\n");
			printf( "/* Depend Files: s.awk/sed.exe/awk.exe                   */\n");
			printf( "/*********************************************************/\n");
			printf( "\n\n\ntypedef struct tag_qy_adaptor \n{\n")
		}
		nlines++;
			
		for (i = 1; i<=NF; i++) 
		{
			idx = index($i,"(" )
			k = 0;
			if( idx > 1 ) 
			{
				k = i;
				break;			
			}
			else if( idx == 1 )
			{					
				k = i-1;								
				break;			
			}				
		}
		
		if( k != 0 )
		{				
			bstar = 0;
			
			strr = substr($k,idx,length($k));
			
			idxstar = index($i,"*" )
			if( idxstar == 1 )
			{
				bstar = 1;					
			}
			strl = substr($k, bstar+1, idx-1-bstar);
		
			printf("\t"); 
			for (i = 1; i<=NF; i++) 
			{
				if( i == k )
				{
					if( bstar == 1 )
					{
						printf("* "); 
					}
					printf("(*qy_%s)%s ",strl, strr );					
				}
				else
					printf("%s ",$i)	
			}
			
			printf("\n");	
		}		
		else
		{
			printf("%s\n",$0)
		}
	}
	
	 
}